// packages/react/src/useGet.ts
import { useRef, useSyncExternalStore } from 'react';
import { useStore } from './provider';

import type { Computed, State } from 'ccstate';

export function useGet<T>(atom: State<T> | Computed<T>) {
  const store = useStore();
  const onChange = useRef((fn: () => void) => {
    const controller = new AbortController();
    store.watch(
      (get) => {
        get(atom);
        fn();
      },
      {
        signal: controller.signal,
      },
    );
    return () => {
      controller.abort();
    };
  });

  return useSyncExternalStore(onChange.current, () => store.get(atom));
}

// packages/solid/src/useGet.ts
import { useStore } from './provider';
import { type Computed, type State } from 'ccstate';
import { createSignal, onCleanup } from 'solid-js';

export function useGet<T>(signal$: State<T> | Computed<T>) {
  const store = useStore();
  const [value, setValue] = createSignal<T>(store.get(signal$));

  const controller = new AbortController();

  store.watch(
    (get) => {
      setValue(() => get(signal$));
    },
    {
      signal: controller.signal,
    },
  );

  onCleanup(() => {
    controller.abort();
  });

  return value;
}
